server:
  port: 8086

spring:
  application:
    name: "proxy"
  sleuth:
    sampler:
      percentage: 1.0
    enabled: true

logging:
  level:
    ROOT: INFO
    proxy: ${LOG_GATEWAY:DEBUG}
    com.hazelcast.cluster: ${LOG_HAZELCAST_CLUSTER:DEBUG}
    org.springframework.web: ${LOG_SPRING_WEB_SOCKET:INFO}
  pattern:
    console: "[%d{yyyy-MM-dd'T'HH:mm:ss.SSS}][lvl=%p][thread=%thread][class=%C{5}][sleuthTraceId=%X{X-B3-TraceId:-}]: %msg%n"

